### ISSUE TITLE
ошибка при автозапуске

### ISSUE THREAD

**Issue by chelnydiablo** [xtrime-ru/NiceHashMinerLegacy-SMA-FIX#1]
выходит ошибка при автозапуске - пустое окошко с кнопкой ОК. видимо остатки от ошибки SMA

нажимаешь ок и стартуешь майнинг вручную

**Comment by xtrime-ru** [comment]
Это не ошибка, там 2 окна, они говорят о том что майнинг пытается автоматически запустится. Оставьте программу в таком состоянии, она сама запустится, как сможет данные получить.
